### ISSUE TITLE
Skopos ground stations ignore their defined AMWTemp in the planner

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/RealAntennas#14]
Partner issue to https://github.com/mockingbirdnest/Skopos/issues/14 since resolving it may demand changes to both mods

The RA antenna planner, both in the VAB and in Flight, will ignore the set AMWTemp value for Skopos ground stations, and instead use the default antenna noise temp for the ground station tech level. This results in the antenna planner dramatically underestimating achievable connection speed, especially at low tech levels where the default AMWTemp is very high.

Actual in-flight performance appears to be correct, and the Antenna debugger reports the correct AMWTemp.

The origin of this problem is [here](https://github.com/KSP-RO/RealAntennas/blob/d8e6dda9440b442140a90884b10de0c9db665f12/src/RealAntennasProject/Physics.cs#L263), where RA for whatever reason fails to identify that Skopos ground stations have a parent body and therefore assumes they are vessel antennas.

**Comment by eggrobin** [comment]
(Probably no change needed to RA for this one.)

**Comment by Capkirk123** [comment]
![image](https://github.com/user-attachments/assets/38987adf-1476-4ddd-9d78-ec26718a317c)

Taking advantage of the new information added to the debugger, we can see that when using the planner, a body is not assigned to the Skopos station, causing [this](https://github.com/KSP-RO/RealAntennas/blob/d8e6dda9440b442140a90884b10de0c9db665f12/src/RealAntennasProject/Physics.cs#L263) to assign it the default AMWTemp instead of the one specified in config. This failure to assign the parent body in the planner occurs in the VAB and in flight.
