### ISSUE TITLE
No power loss from data transfer [Stock]

### ISSUE THREAD

**Issue by Aebestach** [KSP-RO/RealAntennas#36]
Hi, @Capkirk123 can you balance the power consumption for data transmission in the Stock environment? In the current Stock, data transmission for scientific research consumes almost no power.
https://github.com/DRVeyl/RealAntennas/issues/80

**Comment by Capkirk123** [comment]
Probably resolved by https://github.com/KSP-RO/RealAntennas/pull/50 increasing power draw 1000x for stock (or, well, everything that's not RSS)
