### ISSUE TITLE
Unable to edit wiki

### ISSUE THREAD

**Issue by Clayell** [KSP-RO/RealAntennas#39]
Sorry to be so pushy about this, just didn't want to continue pinging kirk. The [wiki](https://github.com/KSP-RO/RealAntennas/wiki) for this repo cannot be edited by people not in the org. The previous [wiki](https://github.com/DRVeyl/RealAntennas/wiki) for RA is fine, as well as other wikis that have been forked from other organizations (like [RSS](https://github.com/KSP-RO/RealSolarSystem/wiki), which actually just links back to the old one but can still be edited by non-org people)
I believe the below instructions should work?
https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

**Comment by siimav** [comment]
Done
