### ISSUE TITLE
How can I keep only ground station icons

### ISSUE THREAD

**Issue by acolasialiuliu** [KSP-RO/RealAntennas#49]
Mods are great, but I'm stupid, I can play normally after removing mod, I like the part showing ground signal stations, I installed krss module. Can I delete some files to achieve this effect?

**Comment by siimav** [comment]
Not sure I understand what you want to see and what not.

**Comment by acolasialiuliu** [comment]
Want to see the ground beacon icon.  You don't want real communication. My answer is translated, probably inaccurate

**Comment by Capkirk123** [comment]
There might be a mod that adds symbols on the map for stock ground stations, leaving them completely unmarked is certainly annoying. It isn't this mod, however.
