### ISSUE TITLE
TS upgrades do not apply if completed in flight scene

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/RealAntennas#6]
The use case is RP-1 simulations that happen in far future where a facility upgrade will get completed.

RP-1 will call `UpgradeableFacility.SetLevel()` which in turn will fire the following events:

- `GameEvents.OnKSCFacilityUpgrading`

- `GameEvents.OnUpgradeableObjLevelChange`

- In a coroutine `GameEvents.OnKSCFacilityUpgraded`

Ref: https://discord.com/channels/319857228905447436/512556346869284864/1144421956649758872

Actually it looks like they do not apply in space center scene either. At least Kerbalism will report wrong data rates until a scene change is done.

Migrated from https://github.com/DRVeyl/RealAntennas/issues/94

**Comment by DRVeyl** [comment]
Add listeners to one of those events and ask the network to reset.
Might be as easy as calling https://github.com/DRVeyl/RealAntennas/blob/master/src/RealAntennasProject/RACommNetScenario.cs#L99 ?
